routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login.login');
})->name('login-dental');

Route::get('/registro', 'PacienteController@create')->name('registro');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('detalle-paciente', 'DetallePacienteController');
    Route::resource('cita', 'CitaController');
    Route::resource('paciente', 'PacienteController');
});

Route::get('hitoria-paciente', function () {
    return view('historia-paciente.index');
})->name('historia-paciente');

Auth::routes();

Route::get('/cita/primera/index', 'PrimeraCitaController@index')
    ->name('primera.cita');
Route::get('/cita/insertar', 'CitaController@ingresar_cita')
    ->name('ingresar.cita');
Route::get('/cita', 'CitaController@index')
    ->name('cita.index');

Route::get('/home', 'HomeController@index')->name('home');


Route::get('role-push', function () {
    $admin = Bouncer::role()->firstOrCreate([
        'name' => 'admin',
        'title' => 'Administrator',
    ]);
    $paciente = Bouncer::role()->firstOrCreate([
        'name' => 'Paciente',
        'title' => 'Paaciente',
    ]);
    $odontologo = Bouncer::role()->firstOrCreate([
        'name' => 'odontologo',
        'title' => 'Odontologo',
    ]);
    $createPrimeraCita = Bouncer::ability()->firstOrCreate([
        'name' => 'primera-cita-odontograma',
        'title' => 'Primera cita',
    ]);
    $createAgendarCita = Bouncer::ability()->firstOrCreate([
        'name' => 'agendar-cita',
        'title' => 'Agendar cita',
    ]);

    Bouncer::allow($admin)->to($createPrimeraCita);
    Bouncer::allow($admin)->to($createAgendarCita);

    (\App\User::findOrFail(1))->assign('admin');
    Bouncer::allow(\App\User::findOrFail(1))->to('primera-cita-odontograma');
});

resources/views/template/head-login.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="images/favicon.ico" type="image/ico"/>

    <title>DentalDesing | @yield('title')</title>

    <!-- Bootstrap -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/dfea41f182.js" crossorigin="anonymous"></script>

    @yield('estilo')

</head>

resources/views/template/head.blade.php
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="images/favicon.ico" type="image/ico" />

    <title>DentalDesing | @yield('title')</title>


      <!-- NProgress -->
      <link href="{{ asset('css/nprogress.css') }}" rel="stylesheet">
      <!-- iCheck -->
      <link href="{{ asset('css/flat/green.css') }}" rel="stylesheet">

      <!-- bootstrap-progressbar -->
      <link href="{{ asset('css/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet">
      <!-- JQVMap -->
      <link href="{{ asset('css/jqvmap.min.css') }}" rel="stylesheet" />
      <!-- bootstrap-daterangepicker -->
      <link href="{{ asset('css/daterangepicker.css') }}" rel="stylesheet">



      <script src="https://kit.fontawesome.com/dfea41f182.js" crossorigin="anonymous"></script>

      <link href="{{ asset('css/app.css') }}" rel="stylesheet">
      <link rel="stylesheet" href="{{ asset('css/custom.css') }}">

      <!-- Custom Theme Style -->
      <link href="{{ asset('css/custom.min.css') }}" rel="stylesheet">

      @yield('estilo')
    <link href="{{ asset('css/base.css') }}" rel="stylesheet">
  </head>

resources/views/template/scripts.blade.php
    <!-- jQuery -->
    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{ asset('js/custom.min.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('js/icheck.min.js') }}"></script>
    <script src="{{ asset('js/sweetalert2.all.min.js') }}"></script>
    @yield('scripts')

resources/views/template/sidebar.blade.php
<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>Menú</h3>
        <ul class="nav side-menu">
            @can('llenar-historia')
                <li><a href='{{ route('detalle-paciente.index') }}'><i class="fas fa-notes-medical"></i> Llenar Historia clínica
                    </a></li>
            @endcan
            @can('ver-historia-clinica')
                <li><a href='{{ route('historia-paciente') }}'><i class="fas fa-notes-medical"></i> Ver Historia clínica
                    </a></li>
            @endcan
            @can('agendar-cita')
                <li><a href='{{ route('cita.index') }}'><i class="fas fa-calendar-alt"></i> Agendar cita </a></li>
                @endcan
                </li>
        </ul>
    </div>

</div>
<!-- /sidebar menu -->