routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('login.login');
})->name('login-dental');

Route::get('/registro', 'PacienteController@create')->name('registro');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('detalle-paciente', 'DetallePacienteController');
    Route::resource('cita', 'CitaController');
    Route::resource('paciente', 'PacienteController');
});

Route::get('hitoria-paciente', function () {
    return view('historia-paciente.index');
})->name('historia-paciente');

Auth::routes();

Route::get('/cita/primera/index', 'PrimeraCitaController@index')
    ->name('primera.cita');
Route::get('/cita/insertar', 'CitaController@ingresar_cita')
    ->name('ingresar.cita');
Route::get('/cita', 'CitaController@index')
    ->name('cita.index');

Route::get('/home', 'HomeController@index')->name('home');


Route::get('role-push', function () {
    $admin = Bouncer::role()->firstOrCreate([
        'name' => 'admin',
        'title' => 'Administrator',
    ]);
    $paciente = Bouncer::role()->firstOrCreate([
        'name' => 'Paciente',
        'title' => 'Paaciente',
    ]);
    $odontologo = Bouncer::role()->firstOrCreate([
        'name' => 'odontologo',
        'title' => 'Odontologo',
    ]);
    $createPrimeraCita = Bouncer::ability()->firstOrCreate([
        'name' => 'primera-cita-odontograma',
        'title' => 'Primera cita',
    ]);
    $createAgendarCita = Bouncer::ability()->firstOrCreate([
        'name' => 'agendar-cita',
        'title' => 'Agendar cita',
    ]);

    Bouncer::allow($admin)->to($createPrimeraCita);
    Bouncer::allow($admin)->to($createAgendarCita);

    (\App\User::findOrFail(1))->assign('admin');
    Bouncer::allow(\App\User::findOrFail(1))->to('primera-cita-odontograma');
});

resources/views/historia-clinica/index.blade.php
@extends('base')

@section('title', 'Historias clínicas')

@section('estilo')
    <link href="{{ asset('css/historia-style.css') }}" rel="stylesheet">
@endsection


@section('content')
    {{--<button class="btn btn-success"><a href='{{ route('primera.cita') }}'>Nuevo</a></button>--}}

        {{--<div class="alert alert-success">
            <h3 > Pacientes </h3>
        </div>--}}

    <h3 class="text-white alert-success pl-2 border" style="width: 150px"> Pacientes </h3>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Paciente</th>
            <th scope="col">N° historia clínica</th>
            <th scope="col">Última visita</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>

        @foreach($pacientes as $paciente)
            <tr>

                <th scope="row">{{ $paciente->primer_nombre }} {{$paciente->primer_apellido}}</th>
                <td>{{ $paciente->cedula }}</td>
                <td> {{substr($paciente->updated_at,0, -9) }}</td>

                <td>
                    <a href='{{ route('detalle-paciente.edit',['detalle_paciente' => $paciente->detalle_paciente]) }}'>
                        <button type="button" class="btn btn-primary">
                            <i class="fas fa-pencil-alt"></i>
                        </button>
                    </a>

                    <a href='{{ route('detalle-paciente.show',['detalle_paciente' => $paciente->detalle_paciente]) }}'>
                        <button type="button" class="btn btn-primary">
                            <i class="fas fa-file-invoice"></i>
                        </button>
                    </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <nav>
        <ul class="pagination">
            <li class="page-item disabled">
                <a class="page-link" href="#">Previous</a>
            </li>
            <li class="page-item active">
                <a class="page-link" href="#">1</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">3</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>


@endsection

@section('scripts')

@endsection